### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by MrHumanRebel** [vicalloy/telegram-shell-bot#21]
nas@nas:~/telegram-shell-bot$  poetry install --only main

  Stack trace:

  11  /usr/lib/python3/dist-packages/clikit/console_application.py:123 in run
      io = io_factory(

  10  /usr/lib/python3/dist-packages/poetry/console/config/application_config.py:221 in create_io
      resolved_command = application.resolve_command(args)

   9  /usr/lib/python3/dist-packages/clikit/console_application.py:110 in resolve_command
      return self._config.command_resolver.resolve(args, self)

   8  /usr/lib/python3/dist-packages/clikit/resolver/default_resolver.py:34 in resolve
      return self.create_resolved_command(result)

   7  /usr/lib/python3/dist-packages/clikit/resolver/default_resolver.py:166 in create_resolved_command
      if not result.is_parsable():

   6  /usr/lib/python3/dist-packages/clikit/resolver/resolve_result.py:43 in is_parsable
      self._parse()

   5  /usr/lib/python3/dist-packages/clikit/resolver/resolve_result.py:49 in _parse
      self._parsed_args = self._command.parse(self._raw_args)

   4  /usr/lib/python3/dist-packages/clikit/api/command/command.py:113 in parse
      return self._config.args_parser.parse(args, self._args_format, lenient)

   3  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:53 in parse
      self._parse(args, _fmt, lenient)

   2  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:101 in _parse
      self._parse_long_option(token, tokens, fmt, lenient)

   1  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:247 in _parse_long_option
      self._add_long_option(name, None, tokens, fmt, lenient)

  NoSuchOptionException

  The "--only" option does not exist.

  at /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│
      302│         option = fmt.get_option(name)
      303│
      304│         if value is False:
nas@nas:~/telegram-shell-bot$  poetry shell

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
nas@nas:~/telegram-shell-bot$ python3 bot.py
Traceback (most recent call last):
  File "/home/nas/telegram-shell-bot/bot.py", line 308, in <module>
    main()
  File "/home/nas/telegram-shell-bot/bot.py", line 274, in main
    dp.add_handler(CallbackQueryHandler(shortcut_cb, run_async=True))
NameError: name 'CallbackQueryHandler' is not defined
nas@nas:~/telegram-shell-bot$

Thanks in advance!

**Comment by guerman5** [comment]
拿到機器我們並沒有做升級,只檢查可以順利進入WEB GUI且短暫使用後確認沒問題而已
Do I need to do an upgrade test? Does it has to be manual by gui, or FOTA(currently detects P01_10 as latest).  FOTA由asus控制 所以我們這邊沒有

如果這樣看來ASUS應該沒有開放最新版本的升級? 我不確定你是否需要升版使用

如果需要新版本 我手邊有
https://askeycloud.askey.com/owncloud/index.php/s/dSGcYUuwhiIZ4uX
PW:Asus
